UASSocialNetwork/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore
from django.conf import settings # type: ignore
from django.conf.urls.static import static # type: ignore

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('notifications.urls')),
    path('', include('core.urls')),
    path('', include('newsfeed.urls')),
    path('', include('friends.urls')),
    path('timeline/', include('userprofile.urls')),
    path('messages/', include('communications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib import admin # type: ignore
from django.urls import path # type: ignore

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

communications/urls.py
from django.urls import path
from .views import *

app_name = "communications"

urlpatterns = [
    path('', all_messages, name="all-messages"),
    path('<slug:friend>', messages_with_one_friend, name="messages-with-one-friend"),
]

core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
]

friends/urls.py
from django.urls import path
from .views import *

app_name = "friends"

urlpatterns = [
    path('find-friends', FindFriendsListView.as_view(), name="find-friends"),
    path('send-request/<slug:username>', send_request, name="send-request"),
    path('accept-request/<slug:friend>', accept_request, name="accept-request"),
]

templates/includes/scripts.html
{% load static %}

<script src="{% static 'js/main.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/newsfeed.js' %}"></script>
<script src="{% static 'js/reconnecting-websocket.js' %}"></script>
<script src="{% static 'js/notifications.js' %}"></script>

templates/includes/sidebar.html
<div class="col-lg-3">
    <aside class="sidebar static">
        <div class="widget">
            <h4 class="widget-title">Shortcuts</h4>
            <ul class="naves">
                <li>
                    <i class="ti-clipboard"></i>
                    <a href="{% url 'core:home' %}" title="">News feed</a>
                </li>
                <li>
                    <i class="ti-mouse-alt"></i>
                    <a href="{% url 'communications:all-messages' %}" title="">Inbox</a>
                </li>
                <li>
                    <i class="ti-user"></i>
                    <a href="{% url 'friends:find-friends' %}" title="">Find Friends</a>
                </li>
                <li>
                    <i class="ti-user"></i>
                    <a href="timeline-friends.html" title="">Friends</a>
                </li>
                {% comment %} <li>
                    <i class="ti-bell"></i>
                    <a href="notifications.html" title="">Notifications</a>
                </li> {% endcomment %}
                <li>
                    <i class="ti-power-off"></i>
                    <a href="{% url 'accounts:logout' %}" title="">Logout</a>
                </li>
            </ul>
        </div><!-- Shortcuts -->
    </aside>
</div><!-- sidebar -->

templates/includes/stylesheets.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/main.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/color.css' %}">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">